<?php
/**
 * Voltika Admin — Cincel Bootstrap (Round 68, 2026-05-22).
 *
 * One-time tool to bootstrap a permanent Cincel API password.
 *
 * Flow per Cincel's official API guide (GUIA_USO_API_CINCEL.pdf):
 *
 *   Step A — Request OTP from Cincel:
 *     GET https://api.cincel.digital/v3/tokens/otp
 *     Authorization: Basic base64(email:"otp")    ← literal word "otp"
 *     Side effect: Cincel emails a 6-digit code to <email>.
 *
 *   Step B — Validate OTP, retrieve JWT, set password:
 *     1. GET /v3/tokens/jwt with Authorization: Basic base64(email:CODE)
 *        Response includes a JWT.
 *     2. Decode JWT payload, extract `sub` (= user_id).
 *     3. PATCH /v3/users/{user_id} with Authorization: Bearer <jwt>
 *        body: {"password": "<NEW_PASSWORD>"}
 *     4. Write CINCEL_EMAIL + CINCEL_PASSWORD into local-secrets.php
 *        (same file-based override mechanism as cincel-creds-setter.php).
 *
 * Once this completes, production code can authenticate with Basic Auth
 * (email:password) on /v3/tokens/jwt indefinitely — no more OTPs.
 *
 * URL: /admin/php/cincel-bootstrap.php
 */

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';
$adminId = adminRequireAuth(['admin']);

// ─────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────

function _cincelApiBase(): string {
    @require_once __DIR__ . '/../../configurador/php/config.php';
    $u = defined('CINCEL_API_URL') ? rtrim(CINCEL_API_URL, '/') : 'https://api.cincel.digital/v3';
    // Some env values include /v3 already; strip it so we can compose paths cleanly.
    return preg_replace('#/v\d+$#', '', $u) ?: 'https://api.cincel.digital';
}

function _cincelEmail(): string {
    @require_once __DIR__ . '/../../configurador/php/config.php';
    return defined('CINCEL_EMAIL') ? CINCEL_EMAIL : (getenv('CINCEL_EMAIL') ?: '');
}

/**
 * Run a single HTTP call to Cincel. Returns [http_code, decoded_body, raw_body, curl_err].
 */
function _cincelCall(string $method, string $url, array $headers, ?string $body = null): array {
    $ch = curl_init($url);
    $opts = [
        CURLOPT_CUSTOMREQUEST  => strtoupper($method),
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADER         => false,
        CURLOPT_TIMEOUT        => 20,
        CURLOPT_CONNECTTIMEOUT => 8,
        CURLOPT_HTTPHEADER     => array_merge(['Accept: application/json'], $headers),
    ];
    if ($body !== null) {
        $opts[CURLOPT_POSTFIELDS] = $body;
    }
    curl_setopt_array($ch, $opts);
    $raw  = curl_exec($ch);
    $code = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $err  = curl_error($ch);
    curl_close($ch);
    $decoded = is_string($raw) ? json_decode($raw, true) : null;
    return [$code, $decoded, $raw, $err ?: null];
}

/**
 * Decode a JWT payload (no signature verification — we just need the `sub`).
 */
function _jwtDecodePayload(string $jwt): ?array {
    $parts = explode('.', $jwt);
    if (count($parts) < 2) return null;
    $payload = $parts[1];
    // Base64URL → base64
    $payload = strtr($payload, '-_', '+/');
    $pad = strlen($payload) % 4;
    if ($pad > 0) $payload .= str_repeat('=', 4 - $pad);
    $raw = base64_decode($payload, true);
    if ($raw === false) return null;
    $obj = json_decode($raw, true);
    return is_array($obj) ? $obj : null;
}

/**
 * Pick the first writable location for local-secrets.php — same list used
 * by cincel-creds-setter.php and config.php.
 */
function _resolveSecretsFile(): array {
    $candidates = [
        __DIR__ . '/../../configurador/php/local-secrets.php',
        __DIR__ . '/../../configurador/php/uploads/voltika-secrets.php',
        __DIR__ . '/../../configurador/php/uploads/firmas/voltika-secrets.php',
        __DIR__ . '/../../configurador/php/contratos/voltika-secrets.php',
        __DIR__ . '/data/voltika-secrets.php',
        sys_get_temp_dir() . '/voltika-secrets.php',
    ];
    foreach ($candidates as $c) {
        $dir = dirname($c);
        if (!is_dir($dir)) @mkdir($dir, 0775, true);
        if (is_dir($dir) && is_writable($dir)) return [$c, true];
        if (file_exists($c) && is_writable($c)) return [$c, true];
    }
    return [$candidates[0], false];
}

function _writeSecretsFile(string $path, string $email, string $password, int $adminId): bool {
    $escEmail = str_replace(["\\", "'"], ["\\\\", "\\'"], $email);
    $escPass  = str_replace(["\\", "'"], ["\\\\", "\\'"], $password);
    $now      = date('Y-m-d H:i:s');
    $contents = <<<PHP
<?php
// Voltika local secrets — auto-generated by cincel-bootstrap.php.
// DO NOT COMMIT this file to git. DO NOT serve it via HTTP directly.
// Last updated: {$now}
// Updated by:   admin id {$adminId}
putenv('CINCEL_EMAIL={$escEmail}');
putenv('CINCEL_PASSWORD={$escPass}');
PHP;
    $bytes = @file_put_contents($path, $contents, LOCK_EX);
    if ($bytes === false) return false;
    @chmod($path, 0640);
    return true;
}

// ─────────────────────────────────────────────────────────────────────────
// POST endpoints (Ajax)
// ─────────────────────────────────────────────────────────────────────────

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json; charset=utf-8');
    $body   = adminJsonIn();
    $action = $body['action'] ?? '';

    // ── Action 1: Request OTP from Cincel ───────────────────────────────
    if ($action === 'request_otp') {
        $email = trim((string)($body['email'] ?? _cincelEmail()));
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            adminJsonOut(['ok' => false, 'error' => 'Email inválido.'], 400);
        }
        $base  = _cincelApiBase();
        $url   = $base . '/v3/tokens/otp';
        $authB64 = base64_encode($email . ':otp');
        [$http, $decoded, $raw, $cErr] = _cincelCall('GET', $url, [
            'Authorization: Basic ' . $authB64,
        ]);
        adminLog('cincel_bootstrap_request_otp', [
            'admin_id' => $adminId,
            'email'    => $email,
            'http'     => $http,
            'ok'       => $http >= 200 && $http < 300,
        ]);
        if ($http >= 200 && $http < 300) {
            adminJsonOut([
                'ok'      => true,
                'message' => 'Cincel envió un código OTP al correo ' . $email . '. Revísalo y úsalo en el paso 2.',
                'http'    => $http,
            ]);
        }
        adminJsonOut([
            'ok'           => false,
            'error'        => 'Cincel rechazó la solicitud de OTP (HTTP ' . $http . ').',
            'http'         => $http,
            'cincel_body'  => $decoded ?: $raw,
            'curl_err'     => $cErr,
            'url'          => $url,
            'hint'         => 'Verifica que CINCEL_API_URL y CINCEL_EMAIL sean correctos. Si Cincel devuelve 401, el correo no está registrado en su sistema.',
        ], 502);
    }

    // ── Action 2: Validate OTP, get JWT, set password, persist ──────────
    if ($action === 'set_password') {
        $email    = trim((string)($body['email']    ?? _cincelEmail()));
        $otpCode  = trim((string)($body['otp_code'] ?? ''));
        $password = (string)($body['password'] ?? '');

        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            adminJsonOut(['ok' => false, 'error' => 'Email inválido.'], 400);
        }
        if (!preg_match('/^[0-9]{4,8}$/', $otpCode)) {
            adminJsonOut(['ok' => false, 'error' => 'OTP debe ser un número de 4 a 8 dígitos.'], 400);
        }
        if (strlen($password) < 10) {
            adminJsonOut(['ok' => false, 'error' => 'La nueva contraseña debe tener al menos 10 caracteres.'], 400);
        }

        $base = _cincelApiBase();

        // ── Step B-1: GET /v3/tokens/jwt with email:OTP ──────────────────
        $jwtUrl = $base . '/v3/tokens/jwt';
        $authB64 = base64_encode($email . ':' . $otpCode);
        [$http1, $decoded1, $raw1, $err1] = _cincelCall('GET', $jwtUrl, [
            'Authorization: Basic ' . $authB64,
        ]);
        if ($http1 < 200 || $http1 >= 300) {
            adminLog('cincel_bootstrap_validate_otp_fail', ['admin_id'=>$adminId, 'http'=>$http1]);
            adminJsonOut([
                'ok'          => false,
                'error'       => 'No se pudo validar el OTP (HTTP ' . $http1 . '). Es muy probable que el código haya expirado — pide uno nuevo y vuelve a intentar.',
                'http'        => $http1,
                'cincel_body' => $decoded1 ?: $raw1,
                'curl_err'    => $err1,
                'step'        => 'validate_otp',
            ], 502);
        }

        // Extract the JWT. Cincel may return { "token": "..." } or { "jwt": "..." }
        // or a bare string — be defensive.
        $jwt = null;
        if (is_array($decoded1)) {
            foreach (['token','jwt','access_token','accessToken'] as $k) {
                if (!empty($decoded1[$k]) && is_string($decoded1[$k])) { $jwt = $decoded1[$k]; break; }
            }
        }
        if (!$jwt && is_string($raw1)) {
            $trim = trim($raw1, " \t\n\r\0\x0B\"");
            if (substr_count($trim, '.') === 2 && preg_match('#^[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+$#', $trim)) {
                $jwt = $trim;
            }
        }
        if (!$jwt) {
            adminJsonOut([
                'ok'          => false,
                'error'       => 'Cincel respondió 200 pero no encontramos el JWT en el body. Revisa la respuesta cruda.',
                'cincel_body' => $decoded1 ?: $raw1,
                'step'        => 'parse_jwt',
            ], 502);
        }

        // ── Step B-2: Decode JWT to extract user_id (sub claim) ─────────
        $payload = _jwtDecodePayload($jwt);
        $userId  = null;
        if (is_array($payload)) {
            foreach (['sub','user_id','userId','id'] as $k) {
                if (isset($payload[$k]) && $payload[$k] !== '') { $userId = $payload[$k]; break; }
            }
        }
        if (!$userId) {
            adminJsonOut([
                'ok'         => false,
                'error'      => 'JWT no contiene un campo sub (user_id) reconocible.',
                'jwt_claims' => $payload,
                'step'       => 'extract_user_id',
            ], 502);
        }

        // ── Step B-3: PATCH /v3/users/{user_id} with Bearer JWT ─────────
        $patchUrl  = $base . '/v3/users/' . rawurlencode((string)$userId);
        $patchBody = json_encode(['password' => $password]);
        [$http2, $decoded2, $raw2, $err2] = _cincelCall('PATCH', $patchUrl, [
            'Authorization: Bearer ' . $jwt,
            'Content-Type: application/json',
        ], $patchBody);
        if ($http2 < 200 || $http2 >= 300) {
            adminLog('cincel_bootstrap_set_password_fail', ['admin_id'=>$adminId, 'http'=>$http2, 'user_id'=>$userId]);
            adminJsonOut([
                'ok'          => false,
                'error'       => 'Cincel rechazó establecer la contraseña (HTTP ' . $http2 . ').',
                'http'        => $http2,
                'cincel_body' => $decoded2 ?: $raw2,
                'curl_err'    => $err2,
                'step'        => 'set_password',
            ], 502);
        }

        // ── Step B-4: Verify by getting a fresh JWT with email:password ──
        $verifyUrl = $base . '/v3/tokens/jwt';
        $verifyB64 = base64_encode($email . ':' . $password);
        [$http3, $decoded3, $raw3, $err3] = _cincelCall('GET', $verifyUrl, [
            'Authorization: Basic ' . $verifyB64,
        ]);
        $verifyOk = ($http3 >= 200 && $http3 < 300);

        // ── Step B-5: Persist to local-secrets.php ──────────────────────
        [$secretsPath, $writable] = _resolveSecretsFile();
        if (!$writable) {
            adminJsonOut([
                'ok'         => false,
                'error'      => 'La contraseña SE ESTABLECIÓ en Cincel correctamente, pero el servidor no pudo escribir local-secrets.php. La contraseña nueva es: ' . $password . ' — guárdala manualmente.',
                'password'   => $password,
                'verify_ok'  => $verifyOk,
                'step'       => 'persist',
            ], 500);
        }
        if (!_writeSecretsFile($secretsPath, $email, $password, $adminId)) {
            adminJsonOut([
                'ok'         => false,
                'error'      => 'La contraseña SE ESTABLECIÓ en Cincel pero falló la escritura del archivo. La contraseña nueva es: ' . $password . ' — guárdala manualmente.',
                'password'   => $password,
                'verify_ok'  => $verifyOk,
                'step'       => 'persist',
            ], 500);
        }

        adminLog('cincel_bootstrap_complete', [
            'admin_id'  => $adminId,
            'email'     => $email,
            'user_id'   => $userId,
            'verify_ok' => $verifyOk,
            'file'      => $secretsPath,
        ]);

        adminJsonOut([
            'ok'        => true,
            'message'   => '✅ Contraseña establecida y guardada. Cincel ahora puede autenticarse con email+password en cada llamada.',
            'user_id'   => $userId,
            'verify_ok' => $verifyOk,
            'file'      => $secretsPath,
        ]);
    }

    adminJsonOut(['ok' => false, 'error' => 'action desconocida'], 400);
}

// ─────────────────────────────────────────────────────────────────────────
// GET: render the UI
// ─────────────────────────────────────────────────────────────────────────

[$secretsPath, $dirOk] = _resolveSecretsFile();
$secretsExists = file_exists($secretsPath);
$currentEmail  = _cincelEmail();
$apiBase       = _cincelApiBase();
$suggestedPw   = bin2hex(random_bytes(12)); // 24-char hex, strong default

header('Content-Type: text/html; charset=utf-8');
?><!doctype html>
<html lang="es"><head><meta charset="utf-8">
<title>Voltika — Cincel Bootstrap</title>
<style>
body{font-family:system-ui,sans-serif;background:#f5f7fb;color:#0c2340;padding:24px;max-width:780px;margin:0 auto;line-height:1.55;}
h1{font-size:22px;margin:0 0 4px;}
h2{font-size:14px;color:#475569;margin:24px 0 8px;text-transform:uppercase;letter-spacing:.4px;}
.muted{color:#94a3b8;font-size:12px;}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:18px;margin-bottom:14px;}
.banner{padding:10px 12px;border-radius:8px;font-size:13px;margin-bottom:10px;}
.banner-ok{background:#dcfce7;border:1px solid #86efac;color:#166534;}
.banner-bad{background:#fee2e2;border:1px solid #fecaca;color:#991b1b;}
.banner-warn{background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;}
.banner-info{background:#dbeafe;border:1px solid #93c5fd;color:#1e40af;}
label{display:block;font-weight:700;font-size:13px;margin:14px 0 4px;color:#334155;}
input[type=email],input[type=text],input[type=password]{width:100%;padding:10px 12px;border:1.5px solid #cbd5e1;border-radius:6px;font-size:14px;font-family:inherit;box-sizing:border-box;}
input:focus{outline:0;border-color:#039fe1;box-shadow:0 0 0 3px rgba(3,159,225,.15);}
button.primary{background:#039fe1;color:#fff;border:0;padding:11px 20px;border-radius:6px;font-weight:700;cursor:pointer;font-size:14px;margin-top:14px;}
button.primary:disabled{background:#94a3b8;cursor:not-allowed;}
button.copy{background:#fff;color:#0c2340;border:1px solid #cbd5e1;padding:5px 10px;border-radius:4px;font-size:11px;cursor:pointer;}
code{background:#1e293b;color:#e2e8f0;padding:2px 6px;border-radius:3px;font-size:11.5px;font-family:ui-monospace,monospace;}
.step{border-left:3px solid #039fe1;padding-left:14px;}
.step.done{border-color:#16a34a;}
.step.idle{border-color:#cbd5e1;opacity:.55;}
.row{display:flex;gap:8px;align-items:center;}
.pw-input{font-family:ui-monospace,monospace;}
pre{background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:10px;font-size:11px;white-space:pre-wrap;word-break:break-all;max-height:240px;overflow:auto;margin:8px 0;}
</style></head><body>

<h1>🔧 Cincel Bootstrap — Establecer contraseña permanente</h1>
<div class="muted">Esta herramienta sigue el flujo oficial de Cincel (GUIA_USO_API_CINCEL.pdf) para convertir una cuenta OTP-only en una cuenta con contraseña fija reutilizable.</div>

<h2>Estado actual</h2>
<div class="card" style="font-size:13px;">
  <div class="row"><strong style="width:170px;">CINCEL_API_URL:</strong> <code><?= htmlspecialchars($apiBase) ?>/v3</code></div>
  <div class="row" style="margin-top:6px;"><strong style="width:170px;">CINCEL_EMAIL actual:</strong> <code><?= htmlspecialchars($currentEmail ?: '(no configurado)') ?></code></div>
  <div class="row" style="margin-top:6px;"><strong style="width:170px;">Archivo de secretos:</strong> <code><?= htmlspecialchars($secretsPath) ?></code></div>
  <div class="row" style="margin-top:6px;"><strong style="width:170px;">¿Escribible?:</strong> <?= $dirOk ? '✅ Sí' : '❌ NO — el bootstrap no podrá guardar' ?></div>
</div>

<h2>Paso 1 — Solicitar OTP a Cincel</h2>
<div class="card step" id="step1">
  <div class="muted" style="margin-bottom:10px;">
    Cincel enviará un código de 6 dígitos al correo que ingreses abajo. El correo debe ser la cuenta registrada en Cincel.
  </div>
  <label for="bsEmail">Correo de la cuenta Cincel</label>
  <input type="email" id="bsEmail" value="<?= htmlspecialchars($currentEmail) ?>" placeholder="oscar@riactor.com" autocomplete="off">
  <button class="primary" id="btnRequest">📩 Solicitar código OTP</button>
  <div id="msg1" style="margin-top:10px;font-size:13px;"></div>
</div>

<h2>Paso 2 — Validar OTP y establecer contraseña permanente</h2>
<div class="card step idle" id="step2">
  <div class="muted" style="margin-bottom:10px;">
    Revisa tu bandeja, copia el código de 6 dígitos y pégalo aquí junto con la contraseña que quieras dejar como permanente. Se generó una contraseña aleatoria fuerte como sugerencia — puedes usarla o reemplazarla.
  </div>
  <label for="bsOtp">Código OTP recibido por correo</label>
  <input type="text" id="bsOtp" inputmode="numeric" maxlength="8" placeholder="123456" autocomplete="off">

  <label for="bsPassword">Nueva contraseña permanente para la API</label>
  <div class="row">
    <input type="text" id="bsPassword" class="pw-input" value="<?= htmlspecialchars($suggestedPw) ?>" autocomplete="off" style="flex:1;">
    <button type="button" class="copy" onclick="document.getElementById('bsPassword').value=Array.from(crypto.getRandomValues(new Uint8Array(12))).map(b=>('0'+b.toString(16)).slice(-2)).join('')">🎲 Generar otra</button>
  </div>
  <div class="muted" style="margin-top:4px;font-size:11.5px;">
    Mínimo 10 caracteres. Esta contraseña se guarda en <code><?= htmlspecialchars($secretsPath) ?></code> y se usa para todas las llamadas automáticas a Cincel — no hace falta que la memorices, pero apúntala en un gestor de contraseñas por si acaso.
  </div>

  <button class="primary" id="btnSetPassword">🔐 Validar OTP y establecer contraseña</button>
  <div id="msg2" style="margin-top:10px;font-size:13px;"></div>
</div>

<h2>¿Cómo funciona?</h2>
<div class="card" style="font-size:13px;">
  <ol style="margin:0;padding-left:20px;line-height:1.7;">
    <li><strong>Paso 1</strong> llama <code>GET /v3/tokens/otp</code> con <code>Authorization: Basic base64(email:"otp")</code> — Cincel envía un código de 6 dígitos al correo.</li>
    <li><strong>Paso 2</strong> hace tres cosas en cadena:
      <ol style="margin-top:4px;padding-left:18px;">
        <li><code>GET /v3/tokens/jwt</code> con <code>Basic base64(email:OTP)</code> → obtiene un JWT.</li>
        <li>Decodifica el JWT, extrae el <code>sub</code> (= user_id de Cincel).</li>
        <li><code>PATCH /v3/users/{user_id}</code> con <code>Bearer &lt;JWT&gt;</code> y body <code>{"password":"..."}</code> → establece la contraseña permanente.</li>
        <li>Verifica que la nueva contraseña funciona pidiendo otro JWT con <code>email:password</code>.</li>
        <li>Escribe <code>CINCEL_EMAIL</code> + <code>CINCEL_PASSWORD</code> a <code>local-secrets.php</code>.</li>
      </ol>
    </li>
    <li>A partir de ese momento, el código de producción usa <code>email:password</code> Basic Auth y obtiene JWT cada vez que lo necesite — sin más OTPs manuales.</li>
  </ol>
</div>

<script>
function setStep(id, state){
  var $el = document.getElementById(id);
  $el.classList.remove('done','idle');
  if (state) $el.classList.add(state);
}
function setMsg(id, text, kind){
  var $el = document.getElementById(id);
  if (!text) { $el.innerHTML = ''; return; }
  var cls = kind === 'ok' ? 'banner-ok' : (kind === 'bad' ? 'banner-bad' : (kind === 'warn' ? 'banner-warn' : 'banner-info'));
  $el.innerHTML = '<div class="banner ' + cls + '">' + text + '</div>';
}

document.getElementById('btnRequest').addEventListener('click', function(){
  var email = document.getElementById('bsEmail').value.trim();
  if (!email) { setMsg('msg1', 'Email requerido.', 'bad'); return; }
  var btn = this;
  btn.disabled = true; btn.textContent = '⏳ Solicitando…';
  setMsg('msg1', '', null);
  fetch(location.pathname, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'request_otp', email: email })
  })
  .then(function(r){ return r.json().then(function(j){ return {http: r.status, body: j}; }); })
  .then(function(res){
    btn.disabled = false; btn.textContent = '📩 Solicitar código OTP';
    if (res.body && res.body.ok) {
      setMsg('msg1', '✅ ' + (res.body.message || 'OTP solicitado correctamente.') + ' Revisa el correo y continúa con el Paso 2 abajo.', 'ok');
      setStep('step1','done');
      setStep('step2',null); // activate Step 2
      document.getElementById('bsOtp').focus();
    } else {
      var err = (res.body && res.body.error) || ('HTTP ' + res.http);
      var detail = res.body && res.body.cincel_body ? '\n\nRespuesta de Cincel:\n' + (typeof res.body.cincel_body === 'string' ? res.body.cincel_body : JSON.stringify(res.body.cincel_body, null, 2)) : '';
      setMsg('msg1', '❌ ' + err + (res.body && res.body.hint ? '<br><span style="font-size:12px;">'+res.body.hint+'</span>' : '') + (detail ? '<pre>' + detail.replace(/[<>&]/g, function(c){ return {'<':'&lt;','>':'&gt;','&':'&amp;'}[c]; }) + '</pre>' : ''), 'bad');
    }
  })
  .catch(function(e){
    btn.disabled = false; btn.textContent = '📩 Solicitar código OTP';
    setMsg('msg1', '❌ Error de red: ' + e.message, 'bad');
  });
});

document.getElementById('btnSetPassword').addEventListener('click', function(){
  var email = document.getElementById('bsEmail').value.trim();
  var otp   = document.getElementById('bsOtp').value.trim();
  var pw    = document.getElementById('bsPassword').value;
  if (!email) { setMsg('msg2', 'Email requerido (vuelve al paso 1).', 'bad'); return; }
  if (!/^[0-9]{4,8}$/.test(otp)) { setMsg('msg2', 'OTP debe ser de 4 a 8 dígitos numéricos.', 'bad'); return; }
  if (pw.length < 10) { setMsg('msg2', 'La contraseña debe tener al menos 10 caracteres.', 'bad'); return; }
  var btn = this;
  btn.disabled = true; btn.textContent = '⏳ Validando + estableciendo…';
  setMsg('msg2', '', null);
  fetch(location.pathname, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'set_password', email: email, otp_code: otp, password: pw })
  })
  .then(function(r){ return r.json().then(function(j){ return {http: r.status, body: j}; }); })
  .then(function(res){
    btn.disabled = false; btn.textContent = '🔐 Validar OTP y establecer contraseña';
    if (res.body && res.body.ok) {
      var msg = '✅ <strong>' + (res.body.message || 'Listo.') + '</strong>';
      msg += '<br>user_id Cincel: <code>' + res.body.user_id + '</code>';
      msg += '<br>verificación: ' + (res.body.verify_ok ? '✅ JWT obtenido con la nueva contraseña' : '⚠ verificación falló (la contraseña se guardó pero no recibimos JWT al re-validar)');
      setMsg('msg2', msg, 'ok');
      setStep('step2','done');
      setTimeout(function(){
        document.body.insertAdjacentHTML('beforeend', '<div class="banner banner-ok" style="margin-top:14px;font-size:14px;">🎉 <strong>Bootstrap completo.</strong> El servidor ya puede firmar con Cincel sin intervención manual. Próximo paso: actualizar el código de producción (Fase 2) para usar GET /v3/tokens/jwt.</div>');
      }, 200);
    } else {
      var err = (res.body && res.body.error) || ('HTTP ' + res.http);
      var step = res.body && res.body.step ? ' (paso: '+res.body.step+')' : '';
      var detail = res.body && res.body.cincel_body ? JSON.stringify(res.body.cincel_body, null, 2) : '';
      setMsg('msg2', '❌ ' + err + step + (detail ? '<pre>' + detail.replace(/[<>&]/g, function(c){ return {'<':'&lt;','>':'&gt;','&':'&amp;'}[c]; }) + '</pre>' : ''), 'bad');
    }
  })
  .catch(function(e){
    btn.disabled = false; btn.textContent = '🔐 Validar OTP y establecer contraseña';
    setMsg('msg2', '❌ Error de red: ' + e.message, 'bad');
  });
});
</script>

</body></html>
