<?php
/**
 * Voltika Admin — Cincel credentials setter (Round 67, 2026-05-22).
 *
 * Plesk on the current hosting plan does NOT expose the "PHP Environment
 * Variables" UI to the admin user. That means CINCEL_EMAIL and
 * CINCEL_PASSWORD are stuck with whatever default ships in config.php
 * (currently the test/dev credentials test@riactor.com / Prueba2026_),
 * which Cincel rejects with "Bad username or password".
 *
 * This page lets an admin paste the production credentials into a form
 * and persists them to /configurador/php/local-secrets.php (a putenv()
 * file that config.php loads BEFORE the constant defines, so the new
 * values win over the env / hardcoded defaults).
 *
 * URL: /admin/php/cincel-creds-setter.php
 *
 * Security notes:
 *   1. Admin-only via existing adminRequireAuth.
 *   2. The secrets file lives inside configurador/php/ — if a request
 *      ever hits it directly via HTTP, PHP executes it (just putenv
 *      calls, zero output), so the contents never leak through HTTP.
 *   3. We deliberately do NOT echo the password back into the form
 *      after a save; the form is one-way.
 *   4. We log only the email + a "password updated yes/no" flag — never
 *      the password itself.
 */

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';
$adminId = adminRequireAuth(['admin']);

$secretsFile = __DIR__ . '/../../configurador/php/local-secrets.php';
$dirOk = is_writable(dirname($secretsFile));

// Read current state without exposing the password.
$currentEmail = '(no configurado)';
$currentPwLen = 0;
$secretsExists = false;
if (file_exists($secretsFile)) {
    $secretsExists = true;
    $raw = (string)@file_get_contents($secretsFile);
    if (preg_match("/putenv\\(\\s*['\"]CINCEL_EMAIL=([^'\"]*)['\"]\\s*\\)/", $raw, $m)) {
        $currentEmail = $m[1];
    }
    if (preg_match("/putenv\\(\\s*['\"]CINCEL_PASSWORD=([^'\"]*)['\"]\\s*\\)/", $raw, $m2)) {
        $currentPwLen = strlen($m2[1]);
    }
}

// Also surface what the application sees at runtime (from getenv after
// the file is loaded) — proves whether the override is effective.
@require_once __DIR__ . '/../../configurador/php/config.php';
$runtimeEmail = defined('CINCEL_EMAIL') ? CINCEL_EMAIL : (getenv('CINCEL_EMAIL') ?: '');
$runtimePwLen = strlen(defined('CINCEL_PASSWORD') ? CINCEL_PASSWORD : (getenv('CINCEL_PASSWORD') ?: ''));

$savedOk = false;
$saveErr = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $newEmail = trim((string)($_POST['cincel_email']    ?? ''));
    $newPass  = (string)($_POST['cincel_password'] ?? '');
    $action   = $_POST['action'] ?? '';

    if ($action === 'clear') {
        if (file_exists($secretsFile) && @unlink($secretsFile)) {
            $savedOk = true;
            adminLog('cincel_creds_cleared', ['admin_id' => $adminId]);
            header('Location: ' . $_SERVER['REQUEST_URI'] . (strpos($_SERVER['REQUEST_URI'], '?') === false ? '?' : '&') . 'cleared=1');
            exit;
        } else {
            $saveErr = 'No se pudo eliminar el archivo (' . $secretsFile . ').';
        }
    } else {
        if ($newEmail === '' || $newPass === '') {
            $saveErr = 'Email y contraseña son requeridos.';
        } elseif (!filter_var($newEmail, FILTER_VALIDATE_EMAIL)) {
            $saveErr = 'El email no tiene un formato válido.';
        } else {
            // Build the file content. We escape quotes/backslashes carefully
            // because the values are inlined inside single-quoted PHP strings.
            $escEmail = str_replace(["\\", "'"], ["\\\\", "\\'"], $newEmail);
            $escPass  = str_replace(["\\", "'"], ["\\\\", "\\'"], $newPass);
            $now      = date('Y-m-d H:i:s');
            $contents = <<<PHP
<?php
// Voltika local secrets — auto-generated by cincel-creds-setter.php.
// DO NOT COMMIT this file to git. DO NOT serve it via HTTP directly.
// It is loaded from configurador/php/config.php on every request.
// Last updated: {$now}
// Updated by: admin id {$adminId}
putenv('CINCEL_EMAIL={$escEmail}');
putenv('CINCEL_PASSWORD={$escPass}');
PHP;

            if (!is_dir(dirname($secretsFile))) {
                $saveErr = 'No existe el directorio destino: ' . dirname($secretsFile);
            } else {
                $wrote = @file_put_contents($secretsFile, $contents, LOCK_EX);
                if ($wrote === false) {
                    $saveErr = 'No se pudo escribir el archivo. Verifica permisos en ' . $secretsFile;
                } else {
                    @chmod($secretsFile, 0640);
                    adminLog('cincel_creds_updated', [
                        'admin_id' => $adminId,
                        'email'    => $newEmail,
                        'password_len' => strlen($newPass),
                    ]);
                    $savedOk = true;
                    // Redirect-after-POST so a refresh doesn't re-submit.
                    header('Location: ' . $_SERVER['REQUEST_URI'] . (strpos($_SERVER['REQUEST_URI'], '?') === false ? '?' : '&') . 'saved=1');
                    exit;
                }
            }
        }
    }
}

$justSaved   = isset($_GET['saved']);
$justCleared = isset($_GET['cleared']);

header('Content-Type: text/html; charset=utf-8');
?><!doctype html>
<html lang="es"><head><meta charset="utf-8">
<title>Voltika — Credenciales Cincel</title>
<style>
body{font-family:system-ui,sans-serif;background:#f5f7fb;color:#0c2340;padding:24px;max-width:760px;margin:0 auto;line-height:1.55;}
h1{font-size:22px;margin:0 0 4px;}
h2{font-size:13px;color:#475569;margin:22px 0 8px;text-transform:uppercase;letter-spacing:.4px;}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:18px;margin-bottom:14px;}
.muted{color:#94a3b8;font-size:12px;}
.banner{padding:10px 12px;border-radius:8px;font-size:13px;margin-bottom:10px;}
.banner-ok{background:#dcfce7;border:1px solid #86efac;color:#166534;}
.banner-bad{background:#fee2e2;border:1px solid #fecaca;color:#991b1b;}
.banner-warn{background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;}
label{display:block;font-weight:700;font-size:13px;margin:14px 0 4px;color:#334155;}
input[type=email], input[type=password]{width:100%;padding:9px 11px;border:1.5px solid #cbd5e1;border-radius:6px;font-size:14px;font-family:inherit;}
input:focus{outline:0;border-color:#039fe1;box-shadow:0 0 0 3px rgba(3,159,225,.15);}
button.primary{background:#039fe1;color:#fff;border:0;padding:11px 20px;border-radius:6px;font-weight:700;cursor:pointer;font-size:14px;margin-top:14px;}
button.danger{background:#fff;color:#dc2626;border:1px solid #dc2626;padding:8px 14px;border-radius:6px;font-weight:600;cursor:pointer;font-size:12px;}
table{width:100%;font-size:13px;}
th{text-align:left;padding:6px 4px;color:#475569;font-weight:700;font-size:11.5px;}
td{padding:6px 4px;}
code{background:#1e293b;color:#e2e8f0;padding:2px 6px;border-radius:3px;font-size:11.5px;font-family:ui-monospace,monospace;}
a{color:#039fe1;}
.warn-note{font-size:11.5px;color:#7c2d12;background:#fff7ed;border:1px solid #fed7aa;padding:8px 10px;border-radius:6px;margin-top:10px;}
</style></head><body>

<h1>🔐 Credenciales Cincel</h1>
<div class="muted">Plesk no expone el editor de variables PHP en este plan — usa este formulario para actualizar las credenciales que Cincel usa para autenticar.</div>

<?php if ($justSaved): ?>
  <div class="banner banner-ok" style="margin-top:14px;">
    ✅ <strong>Credenciales guardadas.</strong> Verifica abajo que los valores "Runtime" coincidan con los que pegaste, y luego corre el diagnóstico:
    <a href="/admin/php/diagnostico-cincel-v2.php?key=voltika_diag_2026" target="_blank">abrir diagnóstico</a>.
  </div>
<?php elseif ($justCleared): ?>
  <div class="banner banner-warn" style="margin-top:14px;">
    Archivo de credenciales eliminado. El sistema volverá a usar las defaults de config.php (las credenciales de prueba).
  </div>
<?php elseif ($saveErr): ?>
  <div class="banner banner-bad" style="margin-top:14px;">
    ❌ <strong>Error:</strong> <?= htmlspecialchars($saveErr) ?>
  </div>
<?php endif; ?>

<h2>Estado actual</h2>
<div class="card">
  <table>
    <tr>
      <th style="width:200px;">Archivo de overrides</th>
      <td><code><?= htmlspecialchars($secretsFile) ?></code></td>
    </tr>
    <tr>
      <th>¿Existe el archivo?</th>
      <td><?= $secretsExists ? '✅ Sí' : '⚠ No (usando defaults de config.php)' ?></td>
    </tr>
    <tr>
      <th>¿Directorio escribible?</th>
      <td><?= $dirOk ? '✅ Sí' : '❌ No — el servidor no puede escribir en ' . htmlspecialchars(dirname($secretsFile)) ?></td>
    </tr>
    <tr>
      <th>Email en el archivo</th>
      <td><code><?= htmlspecialchars($currentEmail) ?></code></td>
    </tr>
    <tr>
      <th>Password en el archivo</th>
      <td><?= $currentPwLen > 0 ? '••• (' . $currentPwLen . ' chars)' : '(vacío)' ?></td>
    </tr>
    <tr>
      <th>Runtime — <code>CINCEL_EMAIL</code></th>
      <td><code><?= htmlspecialchars($runtimeEmail) ?></code></td>
    </tr>
    <tr>
      <th>Runtime — <code>CINCEL_PASSWORD</code></th>
      <td><?= $runtimePwLen > 0 ? '••• (' . $runtimePwLen . ' chars)' : '(vacío)' ?></td>
    </tr>
  </table>
</div>

<h2>Actualizar credenciales</h2>
<div class="card">
  <form method="POST" autocomplete="off">
    <label for="cincel_email">Email Cincel</label>
    <input type="email" id="cincel_email" name="cincel_email" required autocomplete="off"
           value="<?= htmlspecialchars($currentEmail === '(no configurado)' ? '' : $currentEmail) ?>">

    <label for="cincel_password">Password Cincel</label>
    <input type="password" id="cincel_password" name="cincel_password" required autocomplete="new-password"
           placeholder="Pegar la contraseña de producción aquí">

    <div class="warn-note">
      ⚠ Después de guardar, abre <a href="/admin/php/diagnostico-cincel-v2.php?key=voltika_diag_2026" target="_blank">el diagnóstico</a>
      y verifica que el ★ probe de HTTP Basic Auth ahora devuelva HTTP 200 con un JWT.
    </div>

    <button type="submit" class="primary">💾 Guardar credenciales</button>
  </form>
</div>

<?php if ($secretsExists): ?>
<h2>Eliminar archivo (volver a defaults)</h2>
<div class="card">
  <form method="POST" onsubmit="return confirm('¿Eliminar las credenciales actuales? El sistema volverá a usar las de config.php.');">
    <input type="hidden" name="action" value="clear">
    <button type="submit" class="danger">🗑 Eliminar archivo de credenciales</button>
  </form>
</div>
<?php endif; ?>

<h2>¿Cómo funciona?</h2>
<div class="card" style="font-size:13px;">
  <ol style="padding-left:20px;margin:0;">
    <li>Este formulario escribe a <code>configurador/php/local-secrets.php</code>.</li>
    <li>Ese archivo contiene dos llamadas <code>putenv()</code> — nada más.</li>
    <li>Cuando cualquier script de Voltika carga <code>config.php</code>, esa archivo se incluye <strong>antes</strong> de los <code>define()</code>, por lo que <code>getenv('CINCEL_EMAIL')</code> ya devuelve el valor nuevo.</li>
    <li>El archivo NO está en git. No se sirve por HTTP directamente — si alguien lo abre, PHP simplemente lo ejecuta (sin salida).</li>
    <li>Solo admins pueden modificarlo desde aquí. La acción queda en <code>logs_admin</code>.</li>
  </ol>
</div>

</body></html>
