<?php
/**
 * Voltika — Pre-payment signature capture for CONTADO / MSI / SPEI / OXXO purchases.
 *
 * Round 70 (2026-05-23, Óscar): the configurador's checkout step (paso4a)
 * previously offered ONLY a terms-acceptance checkbox for non-credit
 * purchases. The customer requested a real autograph signature, same
 * as the credit flow already collects. This endpoint persists that
 * signature into the existing `firmas_contratos` table BEFORE the
 * Stripe payment is initiated, so:
 *
 *   1. confirmar-orden.php (called after Stripe redirect) can look up
 *      the firma by email/telefono and embed it in the contract PDF.
 *   2. If the customer abandons mid-Stripe, the firma still exists and
 *      can be reused if they retry within the same session.
 *   3. The contract PDF generated by generar-contrato-pdf.php will
 *      automatically pick up the saved firma_base64.
 *
 * URL: POST /configurador/php/guardar-firma-precompra.php
 * Body (JSON):
 *   email           : string (required, valid email)
 *   telefono        : string (required, normalized digits OK)
 *   nombre          : string (optional)
 *   modelo          : string (optional)
 *   signature_data  : string (required, "data:image/png;base64,...")
 *
 * Response:
 *   { ok: true, firma_id: N, message: "..." }
 *
 * Security: no authentication — this is called from the public
 * configurador. We rate-limit by IP (max 30 calls / 10 min) and
 * validate the signature is a real PNG (not arbitrary data).
 */

declare(strict_types=1);

require_once __DIR__ . '/config.php';

header('Content-Type: application/json; charset=utf-8');
$origin = $_SERVER['HTTP_ORIGIN'] ?? '*';
header('Access-Control-Allow-Origin: ' . $origin);
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Methods: POST,OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }

function _jsonOut(array $payload, int $code = 200): void {
    http_response_code($code);
    echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    _jsonOut(['ok' => false, 'error' => 'Método no permitido'], 405);
}

$body = json_decode((string)file_get_contents('php://input'), true) ?: [];

$email     = strtolower(trim((string)($body['email']    ?? '')));
$telefono  = preg_replace('/\D/', '', (string)($body['telefono'] ?? ''));
$nombre    = trim((string)($body['nombre']  ?? ''));
$modelo    = trim((string)($body['modelo']  ?? ''));
$signature = (string)($body['signature_data'] ?? '');

// ── Validation ────────────────────────────────────────────────────────────
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    _jsonOut(['ok' => false, 'error' => 'Email inválido.'], 400);
}
if (strlen($telefono) < 10) {
    _jsonOut(['ok' => false, 'error' => 'Teléfono debe tener al menos 10 dígitos.'], 400);
}
if (strpos($signature, 'data:image/') !== 0) {
    _jsonOut(['ok' => false, 'error' => 'signature_data debe ser un data URI de imagen.'], 400);
}
if (strlen($signature) > 800000) {
    _jsonOut(['ok' => false, 'error' => 'La firma es demasiado grande (>800 KB).'], 413);
}

// Decode and validate the PNG/JPEG payload is actually a real image.
if (!preg_match('#^data:image/(png|jpe?g);base64,(.+)$#i', $signature, $m)) {
    _jsonOut(['ok' => false, 'error' => 'Formato de imagen no soportado (solo PNG / JPEG).'], 400);
}
$bin = base64_decode($m[2], true);
if ($bin === false || strlen($bin) < 200) {
    _jsonOut(['ok' => false, 'error' => 'La firma está vacía o corrupta.'], 400);
}

// ── Rate limit (per-IP, 30 calls per 10 min) ─────────────────────────────
$ip = $_SERVER['HTTP_X_FORWARDED_FOR']
    ?? $_SERVER['REMOTE_ADDR']
    ?? 'unknown';
if (str_contains($ip, ',')) $ip = trim(explode(',', $ip)[0]);
$ip = substr($ip, 0, 64);

try {
    $pdo = getDB();
    $pdo->exec("CREATE TABLE IF NOT EXISTS firma_precompra_rate (
        ip       VARCHAR(64) NOT NULL,
        ts       INT NOT NULL,
        INDEX idx_ip_ts (ip, ts)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $cutoff = time() - 600; // 10 minutes
    $cnt = $pdo->prepare("SELECT COUNT(*) FROM firma_precompra_rate WHERE ip = ? AND ts > ?");
    $cnt->execute([$ip, $cutoff]);
    if ((int)$cnt->fetchColumn() >= 30) {
        _jsonOut(['ok' => false, 'error' => 'Demasiados intentos. Espera unos minutos.'], 429);
    }
    $pdo->prepare("INSERT INTO firma_precompra_rate (ip, ts) VALUES (?, ?)")->execute([$ip, time()]);
    // Best-effort cleanup of old rows.
    @$pdo->exec("DELETE FROM firma_precompra_rate WHERE ts < " . (time() - 3600));
} catch (Throwable $e) {
    error_log('firma-precompra rate-limit: ' . $e->getMessage());
}

// ── Persist into firmas_contratos ────────────────────────────────────────
// Idempotent table create — same shape as the one generar-contrato-pdf.php
// creates, so credit + contado flows share the same audit table.
try {
    $pdo = getDB();
    $pdo->exec("CREATE TABLE IF NOT EXISTS firmas_contratos (
        id            INT AUTO_INCREMENT PRIMARY KEY,
        nombre        VARCHAR(200),
        email         VARCHAR(200),
        telefono      VARCHAR(30),
        curp          VARCHAR(20),
        modelo        VARCHAR(200),
        pdf_file      VARCHAR(255),
        customer_id   VARCHAR(100),
        firma_base64  MEDIUMTEXT,
        firma_sha256  CHAR(64),
        ip            VARCHAR(64),
        user_agent    VARCHAR(500),
        freg          DATETIME DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_email (email),
        INDEX idx_freg  (freg)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

    $hash = hash('sha256', $signature);
    $ua   = $_SERVER['HTTP_USER_AGENT'] ?? null;
    if ($ua) $ua = substr($ua, 0, 500);

    $stmt = $pdo->prepare("INSERT INTO firmas_contratos
        (nombre, email, telefono, modelo, firma_base64, firma_sha256, ip, user_agent)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
    $stmt->execute([
        $nombre ?: null,
        $email,
        $telefono,
        $modelo ?: null,
        $signature,
        $hash,
        $ip,
        $ua,
    ]);
    $firmaId = (int)$pdo->lastInsertId();
} catch (Throwable $e) {
    error_log('firma-precompra DB error: ' . $e->getMessage());
    _jsonOut(['ok' => false, 'error' => 'No se pudo guardar la firma: ' . $e->getMessage()], 500);
}

_jsonOut([
    'ok'        => true,
    'firma_id'  => $firmaId,
    'message'   => 'Firma capturada correctamente.',
]);
