<?php
/**
 * One-shot tool — bulk-regenerate ALL signed Contado/MSI contracts so
 * they pick up today's contract-template fixes (Fecha de pago, Punto
 * autorizado, Fecha estimada de entrega).
 *
 * Customer brief 2026-05-07: existing PDFs were rendered before today's
 * fix to contrato-contado.php / firmar-contrato-checkout-submit.php /
 * descargar-contrato.php and remain on disk with the old "Por definir"
 * placeholder + blank dates. Fixing the code alone doesn't refresh
 * those cached files — admins kept seeing the old contracts. This
 * script walks every Contado/MSI/SPEI/OXXO transaction with a real
 * stripe_pi and forces contratoContadoGenerate() to overwrite the
 * stored PDF with the corrected template output.
 *
 * URL: /configurador/php/regen-contratos-todos.php
 *      ?dry=1   → preview only (default safe mode, no DB / no file writes)
 *      ?run=1   → actually regenerate every contract
 *      ?pedido=VK-2605-0001 → regenerate just one (debugging)
 *
 * Skips: credit-family orders (use generar-contrato-pdf.php) and rows
 *        without a real Stripe PI (synthetic / admin-promoted).
 *
 * Idempotent — re-running just rewrites the same PDFs again with the
 * same contents, so it's safe to invoke multiple times.
 *
 * Auth: same admin gate descargar-contrato.php uses (?admin_key= or
 * portal_session). Without auth the script refuses to run so a leaked
 * URL can't accidentally trigger bulk regenerations from outside.
 */

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/contrato-contado.php';

// ── Auth: align with descargar-contrato.php ─────────────────────────
// Accept either an admin_key matching VOLTIKA_ADMIN_KEY (env / config)
// or an authenticated admin session. Anything else gets a 403.
$adminKey   = (string)($_GET['admin_key'] ?? '');
$expectKey  = defined('VOLTIKA_ADMIN_KEY') ? VOLTIKA_ADMIN_KEY : (getenv('VOLTIKA_ADMIN_KEY') ?: '');
$adminOk    = false;
if ($expectKey !== '' && hash_equals($expectKey, $adminKey)) {
    $adminOk = true;
} else {
    // Fall back to admin session — same approach as other admin tools.
    @session_name('VOLTIKA_ADMIN');
    @session_start();
    if (!empty($_SESSION['admin_user_id'])) $adminOk = true;
}
if (!$adminOk) {
    http_response_code(403);
    header('Content-Type: text/html; charset=utf-8');
    echo '<h1>403 — admin auth requerido</h1><p>Inicia sesión en /admin/ o pasa ?admin_key=…</p>';
    exit;
}

$run        = !empty($_GET['run']);
$onePedido  = trim((string)($_GET['pedido'] ?? ''));
$results    = [];

$pdo = getDB();

// ── Pull every Contado/MSI/SPEI/OXXO transaction with a real Stripe PI.
// We deliberately exclude credit-family rows (tpago in credito/enganche/
// parcial) because those use the credit contract template, not contado.
$where = "t.stripe_pi IS NOT NULL
       AND t.stripe_pi <> ''
       AND t.stripe_pi LIKE 'pi\\_%'
       AND LOWER(TRIM(t.tpago)) NOT IN ('credito','credito-orfano','enganche','parcial')";
$params = [];
if ($onePedido !== '') {
    $where .= " AND t.pedido = ?";
    $params[] = $onePedido;
}
$sql = "SELECT t.* FROM transacciones t WHERE $where ORDER BY t.id DESC";
try {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) {
    http_response_code(500);
    echo 'query failed: ' . htmlspecialchars($e->getMessage());
    exit;
}

// Helper that mirrors descargar-contrato.php's regen-block contratoData.
// Keeping the shapes identical means a contract regenerated by this
// script and one regenerated by descargar-contrato.php?regen=1 are
// byte-for-byte equivalent — admins won't see two flavours of the same
// contract floating around.
function buildContratoData(array $tx): array {
    $tpagoNorm = strtolower((string)($tx['tpago'] ?? ''));
    $total     = floatval($tx['total'] ?: $tx['precio'] ?? 0);
    $costoLog  = (strpos($tpagoNorm, 'msi') !== false) ? 1800 : 0;
    $deliveryPoint = trim((string)($tx['punto_nombre'] ?? ''));
    if ($deliveryPoint !== '' && !empty($tx['ciudad'])) {
        $deliveryPoint .= ' · ' . trim((string)$tx['ciudad']);
    }
    $eta = !empty($tx['fecha_estimada_entrega'])
        ? date('d/m/Y', strtotime((string)$tx['fecha_estimada_entrega']))
        : date('d/m/Y', strtotime('+10 days', strtotime($tx['freg'] ?? 'now')));
    // Customer fix 2026-05-14 (Óscar): pull Cincel audit + sanitize name so
    // bulk regen produces the same clean REGISTRO table as the single-row
    // download path.
    $pdoCx = getDB();
    $cincelAuditBulk = contratoContadoFetchCincelAudit(
        $pdoCx,
        (string)$tx['pedido'],
        isset($tx['id']) ? (int)$tx['id'] : null
    );
    return [
        'pedido'                  => $tx['pedido'],
        'folio'                   => $tx['folio_contrato'] ?: $tx['pedido'],
        'contract_date'           => date('d/m/Y'),
        'customer_full_name'      => contratoContadoSanitizeFullName($tx['nombre'] ?: 'Cliente Voltika'),
        'customer_email'          => $tx['email'] ?? '',
        'customer_phone'          => $tx['telefono'] ?? '',
        'customer_zip'            => $tx['cp'] ?? '',
        'vehicle_model'           => $tx['modelo'] ?? '',
        'vehicle_color'           => $tx['color'] ?? '',
        'vehicle_year'            => (int)date('Y'),
        'vehicle_price'           => $total,
        'logistics_cost'          => (strpos($tpagoNorm, 'msi') !== false) ? $costoLog : 0,
        'total_amount'            => $total,
        'payment_method'          => (strpos($tpagoNorm, 'msi') !== false ? 'msi' : (strpos($tpagoNorm, 'tarjeta') !== false ? 'contado' : $tpagoNorm)),
        'payment_reference'       => $tx['stripe_pi'] ?: $tx['pedido'],
        'payment_date'            => date('d/m/Y H:i', strtotime($tx['freg'] ?? 'now')),
        'estimated_delivery_date' => $eta,
        'delivery_point'          => $deliveryPoint,
        'acceptance_timestamp'    => $tx['contrato_aceptado_at'] ?: ($tx['freg'] ?? gmdate('Y-m-d H:i:s')),
        'acceptance_ip'           => $tx['contrato_aceptado_ip'] ?? '',
        'acceptance_user_agent'   => $tx['contrato_aceptado_ua'] ?? '',
        'otp_validated'           => (int)($tx['contrato_otp_validated'] ?? 0),
        'otp_validated_at'        => $tx['contrato_otp_validated_at'] ?? null,
        'otp_phone_masked'        => $tx['contrato_otp_phone_masked'] ?? null,
        // Cincel / NOM-151 audit (post-Acta-de-Entrega data when present).
        'cincel_document_id'      => $cincelAuditBulk['cincel_document_id'] ?? '',
        'cincel_status'           => $cincelAuditBulk['cincel_status']      ?? '',
        'cincel_signed_at'        => $cincelAuditBulk['cincel_signed_at']   ?? '',
        'cincel_nom151_json'      => $cincelAuditBulk['cincel_nom151_json'] ?? '',
    ];
}

foreach ($rows as $tx) {
    $entry = ['pedido' => $tx['pedido'], 'tpago' => $tx['tpago']];
    if (!$run) {
        $entry['action'] = 'preview';
        $entry['punto']  = $tx['punto_nombre'] ?? '(none)';
        $entry['eta']    = $tx['fecha_estimada_entrega'] ?? '(default freg+10)';
        $results[]       = $entry;
        continue;
    }
    try {
        $contratoData = buildContratoData($tx);
        $r = contratoContadoGenerate($contratoData);
        if (!empty($r['ok']) && !empty($r['path']) && file_exists($r['path'])) {
            $entry['action'] = 'regenerated';
            $entry['path']   = basename($r['path']);
        } else {
            $entry['action'] = 'failed';
            $entry['error']  = $r['error'] ?? 'unknown';
        }
    } catch (Throwable $e) {
        $entry['action'] = 'exception';
        $entry['error']  = $e->getMessage();
    }
    $results[] = $entry;
}

header('Content-Type: text/html; charset=utf-8');
?><!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Regen contratos</title>
<style>
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;background:#0b0f14;color:#eef2f7;padding:32px;max-width:840px;margin:0 auto;line-height:1.5}
h1{color:#22d37a;margin:0 0 12px}
.box{background:#11161d;border:1px solid #202a36;border-radius:12px;padding:20px;margin-bottom:16px}
.row{display:grid;grid-template-columns:140px 110px 1fr;gap:14px;padding:8px 0;border-bottom:1px solid #202a36;font-size:13px;align-items:center}
.row:last-child{border-bottom:0}
.k{color:#9aa7b7;font-family:monospace}
.tag{padding:3px 8px;border-radius:4px;font-size:11px;font-weight:700;text-align:center;font-family:monospace}
.tag.regen{background:rgba(34,211,122,.15);color:#22d37a}
.tag.fail {background:rgba(255,140,140,.15);color:#ff8c8c}
.tag.preview{background:rgba(154,167,183,.2);color:#9aa7b7}
.detail{color:#b7f2cf;font-family:monospace;font-size:11px;word-break:break-all}
.detail.error{color:#ff8c8c}
.btn{background:#22d37a;color:#04120a;border:none;padding:10px 20px;border-radius:8px;font-weight:700;cursor:pointer;font-size:14px;text-decoration:none;display:inline-block;margin-right:8px}
.btn.alt{background:#3b82f6;color:#fff}
code{background:#202a36;padding:2px 6px;border-radius:4px}
.warn{background:rgba(245,179,1,.1);border:1px solid rgba(245,179,1,.35);color:#ffe19a;padding:12px;border-radius:8px;margin-top:16px;font-size:13px}
</style></head><body>

<h1><?= $run ? '✅ Regeneración completada' : '🔍 Modo Preview' ?></h1>
<p style="color:#9aa7b7"><?= count($results) ?> contratos elegibles<?= $onePedido ? ' (filtrado: '.htmlspecialchars($onePedido).')' : '' ?>.</p>

<div class="box">
  <?php if (!$run): ?>
    <p>Click <strong>Regenerar todos</strong> para sobrescribir cada PDF con el template actualizado (Fecha de pago + Punto autorizado + Fecha estimada de entrega).</p>
    <a class="btn" href="?run=1<?= $onePedido ? '&pedido='.urlencode($onePedido) : '' ?><?= $adminKey ? '&admin_key='.urlencode($adminKey) : '' ?>">▶ Regenerar todos</a>
  <?php else: ?>
    <p>Cada PDF de la lista fue reescrito en disco con el template nuevo. Verifica un pedido cualquiera con <code>descargar-contrato.php?pedido=VK-…&inline=1</code>.</p>
  <?php endif; ?>
</div>

<div class="box">
<?php foreach ($results as $r): ?>
  <div class="row">
    <div class="k"><?= htmlspecialchars($r['pedido']) ?></div>
    <div><span class="tag <?= $r['action']==='regenerated'?'regen':($r['action']==='preview'?'preview':'fail') ?>"><?= htmlspecialchars($r['action']) ?></span></div>
    <div class="detail<?= isset($r['error']) ? ' error' : '' ?>">
      <?php if ($r['action']==='preview'): ?>
        tpago=<?= htmlspecialchars($r['tpago']) ?> · punto=<?= htmlspecialchars($r['punto']) ?> · eta=<?= htmlspecialchars($r['eta']) ?>
      <?php elseif (isset($r['error'])): ?>
        ERROR: <?= htmlspecialchars($r['error']) ?>
      <?php else: ?>
        <?= htmlspecialchars($r['path'] ?? '') ?>
      <?php endif; ?>
    </div>
  </div>
<?php endforeach; ?>
</div>

<div class="warn">
  ⚠ Borra <code>regen-contratos-todos.php</code> después de usar — es una herramienta one-shot, no debe quedar accesible en producción.
</div>

</body></html>
